apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-react
  name: nginx-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-react
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-react
    spec:
      containers:
      - image: sawogus29/nginx:react
        name: nginx
        resources: {}
status: {}
