apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-react
  name: nginx-react
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-react
  type: NodePort
status:
  loadBalancer: {}
