apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hhs
  name: hhs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hhs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hhs
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
