apiVersion: v1
kind: Pod
metadata:
  name: test-pd2   #namespace 주석추가
spec:
  containers:
  - image: nginx
    name: web-container
    volumeMounts:
    - mountPath: /data
      name: cache-volume
  - image: busybox
    name: write-container
    command: ['sh','-c','echo hello k8s! && sleep 1000']
    volumeMounts:
    - mountPath: /app
      name: cache-volume
  volumes:
  - name: cache-volume
    persistentVolumeClaim:
        claimName: pvc-sc
  terminationGracePeriodSeconds: 0
  nodeSelector:
    nfs: node2
