apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-pod
  name: nginx-svc
  namespace: default
spec:
  ports:
  - nodePort: 32733
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-pod
  type: NodePort
status:
  loadBalancer: {}
