apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: example
  name: web
  namespace: hhs
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: example
  type: NodePort
status:
  loadBalancer: {}
