apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-21T08:43:24Z"
  labels:
    run: web-pod
  name: web-svc
  namespace: default
  resourceVersion: "18971"
  uid: 255b2537-5ee1-4f73-8bda-2234b3e6f3be
spec:
  clusterIP: 10.103.97.147
  clusterIPs:
  - 10.103.97.147
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32732
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: web-pod
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
