apiVersion: v1
kind: Pod
metadata:
  name: test-pd-cm-env
spec:
  containers:
  - image: nginx
    name: web-container
    env:
    - name: TEST_ENV
      valueFrom:
        configMapKeyRef:
          name: dev-map
          key: B
    volumeMounts:
    - mountPath: /data
      name: cache-volume
  volumes:
  - name: cache-volume
    configMap:
      name: dev-map-2
