apiVersion: v1
kind: Pod
metadata:
  name: test-pd-cm-vol
spec:
  containers:
  - image: nginx
    name: web-container
    volumeMounts:
    - mountPath: /data
      name: cache-volume
  volumes:
  - name: cache-volume
    configMap:
      name: dev-map-2
